driver_greis: fix build with reconfigure disabled
Unhide the definition of greis_parse_input and greis_event_hook since
they are used unconditionally.

Fixes the following build failure:

driver_greis.c:969:25: error: 'greis_parse_input' undeclared here (not in a function); did you mean 'generic_parse_input'?
     .parse_packet     = greis_parse_input,
                         ^~~~~~~~~~~~~~~~~
                         generic_parse_input
driver_greis.c:973:25: error: 'greis_event_hook' undeclared here (not in a function)
     .event_hook       = greis_event_hook,
                         ^~~~~~~~~~~~~~~~

Cc: Gregory Fong <gregory.fong@virginorbit.com>
Signed-off-by: Baruch Siach <baruch@tkos.co.il>
Signed-off-by: Gary E. Miller <gem@rellim.com>