fix building with clock_gettime and newer glibc
Building with recent glibc versions fails in gpsutils.c due to missing
definitions related to clock_gettime.  This is because we define the
_XOPEN_SOURCE macro, but not to a new enough value.  So set it to a
recent spec value that satisfies both strptime and clock_gettime.

Example build failure with glibc-2.15:
gpsutils.c: In function 'timestamp':
gpsutils.c:299:22: error: storage size of 'ts' isn't known
gpsutils.c:300:14: warning: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
gpsutils.c:300:34: error: 'CLOCK_REALTIME' undeclared (first use in this function)
gpsutils.c:300:34: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Eric S. Raymond <esr@thyrsus.com>