Revert "Copy structs using assignment, not memcpy()."
This reverts commit d1965788249d7e22cdde4021d452cf0dc6c6b9bd.

This breaks my build on Gentoo running gcc 4.9.2

libgps_shm.c: In function 'int gps_shm_read(gps_data_t*)':
libgps_shm.c:122:12: error: no match for 'operator=' (operand types are
'gps_data_t' and 'volatile gps_data_t')
  noclobber = shared->gpsdata;
            ^
libgps_shm.c:122:12: note: candidate is:
In file included from gpsd.h:350:0,
                 from libgps_shm.c:30:
gps.h:1918:8: note: gps_data_t& gps_data_t::operator=(const gps_data_t&)
 struct gps_data_t {
        ^
gps.h:1918:8: note:   no known conversion for argument 1 from 'volatile
gps_data_t' to 'const gps_data_t&'