libgps.a: fix building w/dbus support
The current libgps.a logic doesn't pass down pkg-config output from
dbus and such which breaks building when compiling:

gcc -o libgps_dbus.o -c -D_GNU_SOURCE -Wextra -Wall -Wno-uninitialized \
	-Wno-missing-field-initializers -Wcast-align -Wmissing-declarations \
	-Wmissing-prototypes -Wstrict-prototypes -Wpointer-arith -Wreturn-type \
	-O2 libgps_dbus.c
libgps_dbus.c:26:23: fatal error: dbus/dbus.h: No such file or directory
compilation terminated.

Signed-off-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Eric S. Raymond <esr@thyrsus.com>