gpsmon: fix build when reconfigure is false
When reconfigure is False and ncurses support is enabled, the build fails as
follows.

gpsmon.o: In function `gpsd_write':
gpsmon.c:(.text+0xbbc): undefined reference to `monitor_dump_send'
gpsmon.o: In function `main':
gpsmon.c:(.text.startup+0xd68): undefined reference to `announce_log'
collect2: error: ld returned 1 exit status
scons: *** [gpsmon] Error 1
scons: building terminated because of errors.

The problem appears to be a failure to protect calls to momnitor_dump_send
and announce_log with appropriate #ifdef guards.

Signed-off-by: Simon Dawson <spdawson@gmail.com>
Signed-off-by: Eric S. Raymond <esr@thyrsus.com>