fix build error when socket_export is disabled
If you try to build with socket_export disabled, you'll hit a build
failure due to gps_regress being undefined:

NameError: name 'gps_regress' is not defined:
  File "SConstruct", line 1519:
    gps_regress,

Signed-off-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Eric S. Raymond <esr@thyrsus.com>