gpsmon: fix build when nmea is false
When nmea is False and ncurses support is enabled, the build fails as
follows.

gpsmon.o: In function `gpsmon_hook':
gpsmon.c:(.text+0x974): undefined reference to `driver_nmea0183'
collect2: error: ld returned 1 exit status
scons: *** [gpsmon] Error 1
scons: building terminated because of errors.

The problem appears to be a failure to protect use of the driver_nmea0183
variable with appropriate #ifdef guards.

Signed-off-by: Simon Dawson <spdawson@gmail.com>
Signed-off-by: Eric S. Raymond <esr@thyrsus.com>