nmea2000: fix build failures when debugging is disabled
When debugging is disabled, there is no libgps_debuglevel, so building
this driver fails with:
driver_nmea2000.c: In function 'print_data':
driver_nmea2000.c:50:10: error: 'libgps_debuglevel' undeclared (first use in this function)

Add some ifdef to this driver to fix that, and change the return type
of print_data to void since it always returns 0 and no one ever checks
the return value.

Signed-off-by: Mike Frysinger <vapier@gentoo.org>
Signed-off-by: Reinhard Arlt <reinhard.arlt@t-online.de>