gpsd: fix compile error when reconfigure=no
When building with reconfigure=no, the build fails as follows.

  libgpsd_core.c: In function 'gpsd_poll':
  libgpsd_core.c:1236:35: error: 'const struct gps_type_t' has no member named 'mode_switcher'
  scons: *** [libgpsd_core.os] Error 1
  scons: building terminated because of errors.
  make: *** [/scratch/peko/build/gpsd-3.10/.stamp_built] Error 2

The problem appears to be a failure to protect the mode_switcher field with
a RECONFIGURE_ENABLE ifdef.

Signed-off-by: Simon Dawson <spdawson@gmail.com>
Signed-off-by: Eric S. Raymond <esr@thyrsus.com>