Add missing include.
    ntpshmmon.c:34:5: warning: implicit declaration of function 'memset'
    ntpshmmon.c:34:5: warning: incompatible implicit declaration of built-in
function 'memset'